dist: trusty
sudo: required

language: node_js
node_js:
  - '8.11'

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - echo "skipping tests"

before_deploy:
  - npm install claudia -g

deploy:
  provider: script
  script: claudia update
  on:
    branch: master
